server:
  port: 8080
  servlet:
    context-path: /chekzam

spring:
  application:
    name: CHEKZAM
  security:
    user:
      name: root
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/chekzam"
    username: root
    password: 089908
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level.org.hibernate:
      SQL: DEBUG
      Type: TRACE

  web:
    resources:
      static-locations: file:./frontend/build/
    mvc:
      static-path-pattern: "/**"

jwt:
  signerKey: "6VxaHo7rupCMc53uygtXrwKgr29uehBHUfYl69X13u26xdLYZH1XDQU6SJHUXQtR"
  issuer: "CHEKZAM"
  expirationTime: 3
